Repository VerifiedInc/VerifiedInc.github.io, pull requests merged in 2023-08, with the labels that each got.

#111 feature: add docs to composite credential
  docs/acceptance-guide.mdx
  docs/api-overview.mdx
  docs/issuance-guide.mdx
  docs/reusables/credential-request-code-snippet.mdx
  docs/schema.mdx
  docs/terminology.mdx
Labels: 1 min review

#112 [API] intro fix to drop mention of customer creation and brand count.
  docs/acceptance-guide.mdx
  docs/api-overview.mdx
Labels: 1 min review

#113 refactor: rename term required to mandatory
  docs/acceptance-guide.mdx
Labels: 1 min review, single-line

#114 [cleanup] unneeded line.
  docs/acceptance-guide.mdx
Labels: hotfix, 1 min review, single-line

#117 [Acceptance Guide] refactored to promote partner acceptance more prominently. Testing section added. Webhook method mentioned.
  docs/acceptance-guide.mdx
  docs/reusables/atomic-credential-example.mdx
  docs/reusables/composite-credential-example.mdx
  docs/reusables/credential-usage-example-snippet.mdx
  docs/reusables/shared-credentials-body-details.mdx
  docs/reusables/shared-credentials-body.mdx
  docs/terminology.mdx
  package-lock.json
  package.json
Labels: 1 min review

#118 fix: ssn credential data formats.
  docs/1-click-or-free-use-case.mdx
  docs/acceptance-guide.mdx
  docs/issuance-guide.mdx
  docs/reusables/shared-credentials-body.mdx
Labels: 1 min review

#119 [Tracking Identifier] mention in the API and Issuance Guide.
  docs/api-overview.mdx
  docs/issuance-guide.mdx
Labels: 1 min review
