Repository VerifiedInc/VerifiedInc.github.io, pull requests merged in 2024-02, with the labels that each got.

#144 docs: update docs
  docs/1-click-signup.mdx
  docs/api-reference.mdx
  docs/kikoff-guide.mdx
Labels: 1 min review

#145 [Non-Hosted] 1click
  docs/1-click-signup.mdx
  docs/api-reference.mdx
Labels: hotfix, 1 min review

#146 [Non-Hosted] 1 click mention of non url in code only flow.
  docs/1-click-signup.mdx
Labels: 1 min review

#147 [Non-Hosted] typo fixes
  docs/1-click-signup.mdx
  docs/api-reference.mdx
Labels: 1 min review

#148 Adding smsBody attribute and Go Live section
  docs/1-click-signup.mdx
Labels: hotfix

#149 [1Click] SMS sending alignment. Also diagram for non-hosted flow added.
  docs/1-click-signup.mdx
  docs/api-reference.mdx
  docs/kikoff-guide.mdx
Labels: 1 min review

#151 [SMS] 1click diagrams updated with sms production flow.
  docs/1-click-signup.mdx
  docs/kikoff-guide.mdx
Labels: 1 min review

#150 chore: update 1-click links
  docs/demo-1-click-signup.mdx
  static/img/demo-1-click-signup-with-redirect-production.png
  static/img/demo-1-click-signup-with-redirect-production.svg
  static/img/demo-1-click-signup-with-redirect-sandbox.png
  static/img/demo-1-click-signup-with-redirect-sandbox.svg
  static/img/demo-1-click-signup-without-redirect-production.png
  static/img/demo-1-click-signup-without-redirect-production.svg
  static/img/demo-1-click-signup-without-redirect-sandbox.png
  static/img/demo-1-click-signup-without-redirect-sandbox.svg
Labels: 1 min review

#152 Updating go live section with legal language and powered by graphics
  docs/1-click-signup.mdx
  static/img/1-click-signup-powered-by-verified-inc/png/black.png
  static/img/1-click-signup-powered-by-verified-inc/png/gray.png
  static/img/1-click-signup-powered-by-verified-inc/png/green.png
  static/img/1-click-signup-powered-by-verified-inc/png/white.png
  static/img/1-click-signup-powered-by-verified-inc/svg/black.svg
  static/img/1-click-signup-powered-by-verified-inc/svg/gray.svg
  static/img/1-click-signup-powered-by-verified-inc/svg/green.svg
  static/img/1-click-signup-powered-by-verified-inc/svg/white.svg
  static/img/demo-1-click-signup-with-redirect-production.png
  static/img/demo-1-click-signup-with-redirect-sandbox.png
  static/img/demo-1-click-signup-without-redirect-production.png
  static/img/demo-1-click-signup-without-redirect-sandbox.png
  static/img/powered-by-and-legal-language.png
Labels: 1 min review
