Repository VerifiedInc/VerifiedInc.github.io, pull requests merged in 2024-12, with the labels that each got.

#198 feat: add warning about email reliability
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
Labels: 1 min review

#207 Add authentication admonition to quick start guide
  versioned_docs/version-2/1-click-signup/quick-start-guide.mdx
  versioned_docs/version-2/reusables/authentication-admonition.mdx
Labels: 1 min review

#208 Add local testing admonition to integration guide
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/reusables/local-testing-admonition.mdx
Labels: 1 min review

#209 Update Non-Hosted legal language to match other integration types
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
Labels: 1 min review, single-line

#211 Fix anchor links and create reusable component for legal language
  src/components/AnchorOffset.jsx
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/reusables/include-graphic-and-legal-language.mdx
Labels: 1 min review

#214 Update Fraud Signals label to indicate beta status
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
Labels: 1 min review, single-line

#215 Revert "Update Fraud Signals label to indicate beta status"
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
Labels: 1 min review, single-line

#213 [Liam] Fix anchor links and create reusable component for legal language
  src/components/AnchorOffset.jsx
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/reusables/include-graphic-and-legal-language.mdx
Labels: 1 min review

#203 [Liam] Clarify multiple data types and add info about metadata order
  versioned_docs/version-2/1-click-signup/api-reference/types.mdx
  versioned_docs/version-2/reusables/1-click-entity-example.mdx
Labels: 1 min review

#202 [Liam] sequence diagram for all integration types
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/reusables/sequence-diagram-hosted.mdx
  versioned_docs/version-2/reusables/sequence-diagram-non-hosted.mdx
  versioned_docs/version-2/reusables/sequence-diagram-semi-hosted.mdx
Labels: 1 min review

#201 [Liam] feat: add Example App Page
  static/img/slooow.png
  versioned_docs/version-2/1-click-signup/example-app.mdx
Labels: 1 min review

#204 [Liam] Update admonition for masking Social Security Numbers
  versioned_docs/version-2/reusables/prompt-user-to-confirm-their-data.mdx
Labels: 1 min review, single-line

#205 [Liam] Add customer_otp verification method
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
Labels: 1 min review

#216 Swagger postman endpoints
  src/components/Buttons/PostmanButton.jsx
  src/components/Buttons/SwaggerButton.jsx
  src/css/custom.css
  versioned_docs/version-2/1-click-signup/api-reference/endpoints.mdx
  versioned_docs/version-2/reusables/EndpointHeader.jsx
Labels: 5 min review

#217 fix: update import paths for PostmanButton and SwaggerButton components
  src/components/EndpointHeader.jsx
  versioned_docs/version-2/1-click-signup/api-reference/endpoints.mdx
Labels: 1 min review

#220 riskSignalsFeedback
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
  versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
  versioned_docs/version-2/1-click-signup/api-reference/types.mdx
Labels: 1 min review

#222 Merge main into dev so we can merge dev into main
  versioned_docs/version-2/1-click-signup/api-reference/endpoints.mdx
Labels: 1 min review

#221 Releasing changes into main
  src/components/AnchorOffset.jsx
  src/components/Buttons/PostmanButton.jsx
  src/components/Buttons/SwaggerButton.jsx
  src/components/EndpointHeader.jsx
  src/css/custom.css
  static/img/slooow.png
  versioned_docs/version-1/1-click-signup.mdx
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
  versioned_docs/version-2/1-click-signup/api-reference/endpoints.mdx
  versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
  versioned_docs/version-2/1-click-signup/api-reference/types.mdx
  versioned_docs/version-2/1-click-signup/example-app.mdx
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/1-click-signup/migration-guide-v1-to-v2.mdx
  versioned_docs/version-2/1-click-signup/quick-start-guide.mdx
  versioned_docs/version-2/reusables/1-click-entity-example.mdx
  versioned_docs/version-2/reusables/authentication-admonition.mdx
  versioned_docs/version-2/reusables/include-graphic-and-legal-language.mdx
  versioned_docs/version-2/reusables/local-testing-admonition.mdx
  versioned_docs/version-2/reusables/post-1-click-request-body-table-shared.mdx
  versioned_docs/version-2/reusables/prompt-user-to-confirm-their-data.mdx
  versioned_docs/version-2/reusables/sequence-diagram-hosted.mdx
  versioned_docs/version-2/reusables/sequence-diagram-non-hosted.mdx
  versioned_docs/version-2/reusables/sequence-diagram-semi-hosted.mdx
Labels: 5 min review

#223 Various changes based on business team feedback
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
  versioned_docs/version-2/1-click-signup/api-reference/types.mdx
  versioned_docs/version-2/1-click-signup/demo.mdx
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/1-click-signup/migration-guide-v1-to-v2.mdx
  versioned_docs/version-2/1-click-signup/quick-start-guide.mdx
  versioned_docs/version-2/reusables/error-example-oce017.mdx
  versioned_docs/version-2/reusables/error-type.mdx
  versioned_docs/version-2/reusables/setup-login-to-dashboard.mdx
Labels: 1 min review

#224 Updates based on team feedback
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
  versioned_docs/version-2/1-click-signup/api-reference/types.mdx
  versioned_docs/version-2/1-click-signup/demo.mdx
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/1-click-signup/migration-guide-v1-to-v2.mdx
  versioned_docs/version-2/1-click-signup/quick-start-guide.mdx
  versioned_docs/version-2/reusables/error-example-oce017.mdx
  versioned_docs/version-2/reusables/error-type.mdx
  versioned_docs/version-2/reusables/setup-login-to-dashboard.mdx
Labels: 1 min review

#225 Hiding Overview page
  versioned_docs/version-2/1-click-signup/overview.mdx
Labels: 1 min review, single-line

#226 Hiding Overview page
  versioned_docs/version-2/1-click-signup/overview.mdx
Labels: 1 min review, single-line

#227 comment just to test the Squash merge option from dev to main
  versioned_docs/version-2/1-click-signup/api-reference/types.mdx
Labels: 1 min review, single-line

#229 comment just to test the Rebase merge option from dev to main
  versioned_docs/version-2/1-click-signup/api-reference/types.mdx
Labels: 1 min review, single-line

#230 Updated values for RiskSignals type, linked to Risk Signals on Data page, added warnings for not using API keys client side
  versioned_docs/version-2/1-click-signup/api-reference/types.mdx
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/reusables/api-keys-admonition.mdx
  versioned_docs/version-2/reusables/prompt-user-to-confirm-their-data.mdx
Labels: 1 min review

#231 RiskSignals, API Keys warnings
  versioned_docs/version-2/1-click-signup/api-reference/types.mdx
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/reusables/api-keys-admonition.mdx
  versioned_docs/version-2/reusables/prompt-user-to-confirm-their-data.mdx
Labels: 1 min review

#232 Creates collapsable component and adds to Example App page
  package-lock.json
  src/components/Collapsable.jsx
  src/css/custom.css
  versioned_docs/version-2/1-click-signup/example-app.mdx
Labels: 10 min review

#235 Remove transition and add integration-guide
  src/components/Collapsable.jsx
  src/components/ScrollToHash.jsx
  src/css/custom.css
  src/theme/Root.js
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
  versioned_docs/version-2/1-click-signup/api-reference/endpoints.mdx
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/1-click-signup/quick-start-guide.mdx
Labels: 5 min review

#240 [1-Click] errors updated to include OCE 18 & 19
  versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/reusables/error-type.mdx
  versioned_docs/version-2/reusables/when-step-is-necessary-admonition.mdx
Labels: 1 min review

#241 [1-Click] new OCE 18 & 19 retry error codes
  docusaurus.config.js
  package-lock.json
  src/components/Buttons/NavbarButton.jsx
  src/components/Buttons/PostmanButton.jsx
  src/components/Buttons/SwaggerButton.jsx
  src/components/Collapsable.jsx
  src/components/ScrollToHash.jsx
  src/css/custom.css
  src/theme/NavbarItem/ComponentTypes.js
  src/theme/Root.js
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
  versioned_docs/version-2/1-click-signup/api-reference/endpoints.mdx
  versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
  versioned_docs/version-2/1-click-signup/example-app.mdx
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/1-click-signup/quick-start-guide.mdx
  versioned_docs/version-2/reusables/error-type.mdx
  versioned_docs/version-2/reusables/when-step-is-necessary-admonition.mdx
Labels: 20 min review

#242 fix: fix metadata being collapsed when it was not supposed to
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
Labels: hotfix, 1 min review

#243 fix: fix metadata being collapsed when it was not supposed to
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
Labels: hotfix, 1 min review

#244 bump minor packages
  package-lock.json
  package.json
Labels: 1 min review
