Repository VerifiedInc/VerifiedInc.github.io, pull requests merged in 2024-01, with the labels that each got.

#133 Docs Revamp for 1-Click Signup
  api/specs/api.json
  docs/1-click-signup.mdx
  docs/about-unum-id.mdx
  docs/api-overview.mdx
  docs/demos.mdx
  docs/issue-to-earn.mdx
  docusaurus.config.js
  package-lock.json
  package.json
  sidebars.js
  src/theme/ReactLiveScope/index.js
Labels: 30 min review

#135 Further documentation updates.
  docs/1-click-or-free-use-case.mdx
  docs/1-click-signup.mdx
  docs/api-reference.mdx
  docs/demo-issue-to-earn.mdx
  docs/issuance-guide.mdx
  docs/issue-to-earn.mdx
  docs/reusables/sandbox-testing-credentials.mdx
Labels: 1 min review

#134 More docs revamp, mostly focused on Issue to Earn
  docs/1-click-or-free-use-case.mdx
  docs/1-click-signup.mdx
  docs/api-reference.mdx
  docs/demo-1-click-signup.mdx
  docs/demo-issue-to-earn.mdx
  docs/issuance-guide.mdx
  docs/issue-to-earn.mdx
  docs/reusables/sandbox-testing-credentials.mdx
  docs/terminology.mdx
  docusaurus.config.js
  sidebars.js
  src/components/Tip.jsx
Labels: 5 min review

#136 [Draft] removed form issue to earn page.
  docs/issue-to-earn.mdx
Labels: hotfix

#137 Fixes and Kikoff guide
  docs/1-click-signup.mdx
  docs/demo-1-click-signup.mdx
  docs/kikoff-1-click-signup.mdx
  static/img/text-credit-to-signup.svg
Labels: 1 min review

#138 Recommending no redirect in Kikoff Guide
  docs/demo-1-click-signup.mdx
  docs/kikoff-1-click-signup.mdx
  static/img/demo-1-click-signup-with-redirect-production.svg
  static/img/demo-1-click-signup-with-redirect-sandbox.svg
  static/img/demo-1-click-signup-without-redirect-production.svg
  static/img/demo-1-click-signup-without-redirect-sandbox.svg
  static/img/kikoff/1-Click Signup - Data.png
  static/img/kikoff/1-Click Signup - Phone.png
  static/img/kikoff/1-Click Signup - Verify Phone.png
  static/img/kikoff/Existing Signup - Address.png
  static/img/kikoff/Existing Signup - DOB.png
  static/img/kikoff/Existing Signup - Email and Password.png
  static/img/kikoff/Existing Signup - Name.png
  static/img/kikoff/Existing Signup - Phone.png
  static/img/kikoff/Existing Signup - SSN.png
  static/img/kikoff/Existing Signup - Submit.png
  static/img/kikoff/Existing Signup - Verify Email.png
  static/img/kikoff/Existing Signup - Verify Phone.png
  static/img/kikoff/text-credit-to-signup.svg
Labels: 1 min review

#139 chore: added email and redirect to api-reference
  docs/api-reference.mdx
Labels: 1 min review

#140 Typo fixes, small changes to API Overview page
  docs/api-reference.mdx
  docs/kikoff-guide.mdx
  docs/reusables/sandbox-testing-credentials.mdx
Labels: 1 min review

#141 [Typedoc] link updated to core-types.
  docs/api-reference.mdx
Labels: hotfix, 1 min review, single-line

#142 Updating Kikoff guide to mention upcoming change to format of data we send them
  docs/api-reference.mdx
  docs/kikoff-guide.mdx
Labels: 1 min review
