Repository VerifiedInc/VerifiedInc.github.io, pull requests merged in 2025-03, with the labels that each got.

#259 Fixing error typo
  versioned_docs/version-2/reusables/error-type.mdx
Labels: 1 min review, single-line

#261 Making various small updates
  docusaurus.config.js
  package-lock.json
  package.json
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/reusables/errors/OCE011.mdx
  versioned_docs/version-2/reusables/sequence-diagram-non-hosted.mdx
  versioned_docs/version-2/reusables/sequence-diagram-semi-hosted.mdx
Labels: 1 min review

#262 fix: error display component text
  src/components/ErrorDisplay.jsx
Labels: 1 min review, single-line

#263 recommendedUx
  src/components/Buttons/NavbarButton.jsx
  src/components/ColorIndicator.jsx
  src/components/ComponentTypeIndicator.jsx
  src/components/Grid.jsx
  src/css/custom.css
  static/img/color-indicators/background.svg
  static/img/color-indicators/error.svg
  static/img/color-indicators/muted.svg
  static/img/color-indicators/primary.svg
  static/img/component-type-indicators/alert.svg
  static/img/component-type-indicators/button.svg
  static/img/component-type-indicators/graphic.svg
  static/img/component-type-indicators/input.svg
  static/img/component-type-indicators/modal.svg
  static/img/component-type-indicators/snackbar.svg
  static/img/component-type-indicators/text.svg
  static/img/flow_chart-api-non_hosted.png
  static/img/recommended-ux-screens/birthday-empty.png
  static/img/recommended-ux-screens/birthday-error.png
  static/img/recommended-ux-screens/info-edit.png
  static/img/recommended-ux-screens/info-manual_signup.png
  static/img/recommended-ux-screens/info-view-tooltip_hidden.png
  static/img/recommended-ux-screens/info-view-tooltip_visible.png
  static/img/recommended-ux-screens/phone-empty.png
  static/img/recommended-ux-screens/phone-error.png
  static/img/recommended-ux-screens/verification_code-empty.png
  static/img/recommended-ux-screens/verification_code-error.png
  static/img/recommended-ux-screens/verification_code-resent.png
  versioned_docs/version-2/1-click-signup/recommended-ux.mdx
  versioned_docs/version-2/reusables/include-powered-by-graphic.mdx
  versioned_docs/version-2/reusables/powered-by-graphic.mdx
Labels: 1 min review

#265 Tweaking Recommended UX page based on Aidan's feedback
  static/img/1-click-signup-powered-by-verified-inc/png/black.png
  static/img/1-click-signup-powered-by-verified-inc/png/gray.png
  static/img/1-click-signup-powered-by-verified-inc/png/green.png
  static/img/1-click-signup-powered-by-verified-inc/png/white.png
  static/img/1-click-signup-powered-by-verified-inc/svg/black.svg
  static/img/1-click-signup-powered-by-verified-inc/svg/gray.svg
  static/img/1-click-signup-powered-by-verified-inc/svg/green.svg
  static/img/1-click-signup-powered-by-verified-inc/svg/white.svg
  static/img/graphics/1-click-access-powered-by-verified/png/black.png
  static/img/graphics/1-click-access-powered-by-verified/png/gray.png
  static/img/graphics/1-click-access-powered-by-verified/png/green.png
  static/img/graphics/1-click-access-powered-by-verified/png/white.png
  static/img/graphics/1-click-access-powered-by-verified/svg/black.svg
  static/img/graphics/1-click-access-powered-by-verified/svg/gray.svg
  static/img/graphics/1-click-access-powered-by-verified/svg/green.svg
  static/img/graphics/1-click-access-powered-by-verified/svg/white.svg
  static/img/graphics/1-click-apply-powered-by-verified/png/black.png
  static/img/graphics/1-click-apply-powered-by-verified/png/gray.png
  static/img/graphics/1-click-apply-powered-by-verified/png/green.png
  static/img/graphics/1-click-apply-powered-by-verified/png/white.png
  static/img/graphics/1-click-apply-powered-by-verified/svg/black.svg
  static/img/graphics/1-click-apply-powered-by-verified/svg/gray.svg
  static/img/graphics/1-click-apply-powered-by-verified/svg/green.svg
  static/img/graphics/1-click-apply-powered-by-verified/svg/white.svg
  static/img/graphics/1-click-autofill-powered-by-verified/png/black.png
  static/img/graphics/1-click-autofill-powered-by-verified/png/gray.png
  static/img/graphics/1-click-autofill-powered-by-verified/png/green.png
  static/img/graphics/1-click-autofill-powered-by-verified/png/white.png
  static/img/graphics/1-click-autofill-powered-by-verified/svg/black.svg
  static/img/graphics/1-click-autofill-powered-by-verified/svg/gray.svg
  static/img/graphics/1-click-autofill-powered-by-verified/svg/green.svg
  static/img/graphics/1-click-autofill-powered-by-verified/svg/white.svg
  static/img/graphics/1-click-login-powered-by-verified/png/black.png
  static/img/graphics/1-click-login-powered-by-verified/png/gray.png
  static/img/graphics/1-click-login-powered-by-verified/png/green.png
  static/img/graphics/1-click-login-powered-by-verified/png/white.png
  static/img/graphics/1-click-login-powered-by-verified/svg/black.svg
  static/img/graphics/1-click-login-powered-by-verified/svg/gray.svg
  static/img/graphics/1-click-login-powered-by-verified/svg/green.svg
  static/img/graphics/1-click-login-powered-by-verified/svg/white.svg
  static/img/graphics/1-click-signup-powered-by-verified/png/black.png
  static/img/graphics/1-click-signup-powered-by-verified/png/gray.png
  static/img/graphics/1-click-signup-powered-by-verified/png/green.png
  static/img/graphics/1-click-signup-powered-by-verified/png/white.png
  static/img/graphics/1-click-signup-powered-by-verified/svg/black.svg
  static/img/graphics/1-click-signup-powered-by-verified/svg/gray.svg
  static/img/graphics/1-click-signup-powered-by-verified/svg/green.svg
  static/img/graphics/1-click-signup-powered-by-verified/svg/white.svg
  static/img/graphics/1-click-verify-powered-by-verified/png/black.png
  static/img/graphics/1-click-verify-powered-by-verified/png/gray.png
  static/img/graphics/1-click-verify-powered-by-verified/png/green.png
  static/img/graphics/1-click-verify-powered-by-verified/png/white.png
  static/img/graphics/1-click-verify-powered-by-verified/svg/black.svg
  static/img/graphics/1-click-verify-powered-by-verified/svg/gray.svg
  static/img/graphics/1-click-verify-powered-by-verified/svg/green.svg
  static/img/graphics/1-click-verify-powered-by-verified/svg/white.svg
  versioned_docs/version-2/1-click-signup/recommended-ux.mdx
  versioned_docs/version-2/reusables/include-a-powered-by-graphic.mdx
  versioned_docs/version-2/reusables/powered-by-graphic.mdx
Labels: 1 min review

#266 [Test Users] typo fix
  versioned_docs/version-2/1-click-signup/api-reference/test-users.mdx
Labels: hotfix, 1 min review, single-line

#267 [Test Users] revamped with new values. Additional Telesign test users added.
  api/specs/api.json
  src/components/Tip.jsx
  versioned_docs/version-1/1-click-signup.mdx
  versioned_docs/version-1/api-reference.mdx
  versioned_docs/version-1/demo-1-click-signup.mdx
  versioned_docs/version-1/reusables/sandbox-testing-credentials.mdx
  versioned_docs/version-1/terminology.mdx
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
  versioned_docs/version-2/1-click-signup/api-reference/test-users.mdx
  versioned_docs/version-2/reusables/1-click-entity-example.mdx
  versioned_docs/version-2/reusables/errors/OCE002.mdx
  versioned_docs/version-2/reusables/post-1-click-request-body-table-shared.mdx
  versioned_docs/version-2/reusables/post-1-click-response-body-table-url.mdx
  versioned_docs/version-2/reusables/supported-phone-numbers-admonition.mdx
Labels: 5 min review

#268 [Test Users] updated to match latest mocker updates
  versioned_docs/version-2/1-click-signup/api-reference/test-users.mdx
Labels: 1 min review, single-line
