Repository VerifiedInc/VerifiedInc.github.io, pull requests merged in 2025-01, with the labels that each got.

#246 [Error Codes] OCE020 documentation added.
  versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
  versioned_docs/version-2/reusables/error-type.mdx
Labels: 1 min review

#236 feat: add Reusable Error codes and Most Common section
  package-lock.json
  package.json
  src/components/ErrorDisplay.jsx
  src/css/custom.css
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
  versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
  versioned_docs/version-2/reusables/errors/OCE001.mdx
  versioned_docs/version-2/reusables/errors/OCE002.mdx
  versioned_docs/version-2/reusables/errors/OCE007.mdx
  versioned_docs/version-2/reusables/errors/OCE008.mdx
  versioned_docs/version-2/reusables/errors/OCE011.mdx
  versioned_docs/version-2/reusables/errors/OCE012.mdx
  versioned_docs/version-2/reusables/errors/OCE013.mdx
  versioned_docs/version-2/reusables/errors/OCE015.mdx
  versioned_docs/version-2/reusables/errors/OCE016.mdx
  versioned_docs/version-2/reusables/errors/OCE017.mdx
  versioned_docs/version-2/reusables/errors/OCE018.mdx
  versioned_docs/version-2/reusables/errors/OCE019.mdx
Labels: 1 min review

#239 feat: add custom demo component and update demo page
  src/components/Buttons/LinkedInButton.jsx
  src/components/DemoEmailForm.jsx
  src/css/custom.css
  versioned_docs/version-2/1-click-signup/demo.mdx
  versioned_docs/version-2/reusables/setup-login-to-dashboard.mdx
  versioned_docs/version-2/reusables/work-email-admonition.mdx
Labels: 20 min review

#247 [Errors] removed OCE020 error code reference.
  versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
  versioned_docs/version-2/reusables/error-type.mdx
Labels: 1 min review

#249 [CI] Github Action for tag base Vercel Production & Preview deployments setup.
  .github/workflows/deploy.yaml
  .github/workflows/preview.yaml
  .gitignore
  README.md
  vercel.json
Labels: 5 min review, approve

#252 [README] updated with latest deployment info.
  README.md
Labels: 1 min review, single-line

#253 [Demo] page updated
  src/components/DemoEmailForm.jsx
  src/css/custom.css
  versioned_docs/version-2/1-click-signup/api-reference/test-users.mdx
  versioned_docs/version-2/1-click-signup/demo.mdx
Labels: 1 min review

#254 fix: two collapsable bugs
  src/components/Collapsable.jsx
  versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
Labels: 1 min review

#255 Updates across many files to add support for SSN4 input
  src/components/Collapsible.jsx
  src/components/ErrorDisplay.jsx
  src/css/custom.css
  versioned_docs/version-2/1-click-signup/api-reference/authentication.mdx
  versioned_docs/version-2/1-click-signup/api-reference/data.mdx
  versioned_docs/version-2/1-click-signup/api-reference/endpoints.mdx
  versioned_docs/version-2/1-click-signup/api-reference/errors.mdx
  versioned_docs/version-2/1-click-signup/api-reference/test-users.mdx
  versioned_docs/version-2/1-click-signup/example-app.mdx
  versioned_docs/version-2/1-click-signup/integration-guide.mdx
  versioned_docs/version-2/1-click-signup/migration-guide-v1-to-v2.mdx
  versioned_docs/version-2/1-click-signup/overview.mdx
  versioned_docs/version-2/1-click-signup/quick-start-guide.mdx
  versioned_docs/version-2/reusables/birth-date-over-ssn4-admonition.mdx
  versioned_docs/version-2/reusables/development-work-admonition.mdx
  versioned_docs/version-2/reusables/error-example-oce011.mdx
  versioned_docs/version-2/reusables/error-type.mdx
  versioned_docs/version-2/reusables/errors/OCE011.mdx
  versioned_docs/version-2/reusables/errors/OCE012.mdx
  versioned_docs/version-2/reusables/errors/OCE019.mdx
  versioned_docs/version-2/reusables/how-to-test-admonition.mdx
  versioned_docs/version-2/reusables/include-additional-info-if-possible-admonition.mdx
  versioned_docs/version-2/reusables/include-birth-date-if-possible-admonition.mdx
  versioned_docs/version-2/reusables/post-1-click-request-body-table-hosted.mdx
  versioned_docs/version-2/reusables/post-1-click-request-body-table-shared.mdx
  versioned_docs/version-2/reusables/sandbox-birth-date-admonition.mdx
  versioned_docs/version-2/reusables/sandbox-validation-admonition.mdx
  versioned_docs/version-2/reusables/sequence-diagram-hosted.mdx
  versioned_docs/version-2/reusables/sequence-diagram-non-hosted.mdx
  versioned_docs/version-2/reusables/sequence-diagram-semi-hosted.mdx
  versioned_docs/version-2/reusables/use-your-own-phone-number-admonition.mdx
  versioned_docs/version-2/reusables/when-step-is-necessary-admonition.mdx
Labels: 1 min review

#256 Adding various new test users
  versioned_docs/version-2/1-click-signup/api-reference/test-users.mdx
  versioned_docs/version-2/reusables/error-type.mdx
Labels: 1 min review
